package com.sabalapps.arrowescape.game

import java.io.File
import java.util.Locale
import kotlin.random.Random
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Writes the development-only difficulty report and asserts the curve has no
 * cliffs in it. The report goes to `app/build/reports/levels/` — it is a
 * design tool, and nothing in it is ever shown to a player.
 *
 * The difficulty number is **scanning effort**: at each step a player has to
 * look at roughly `arrows remaining / arrows currently free` arrows before
 * finding a legal one, and the level's effort is that summed over a full
 * clear, averaged over many random clears. It rises both with board size and
 * with how tightly the arrows block each other, which is what actually makes a
 * level feel hard here.
 */
class LevelDifficultyReportTest {

    private data class Row(
        val level: Level,
        val initiallyValidMoves: Int,
        val solutionLength: Int,
        val solvable: Boolean,
        val effort: Double
    )

    private fun analyse(level: Level): Row {
        val outcome = LevelSolver.solve(level)
        val solved = outcome as? LevelSolver.Outcome.Solved
        return Row(
            level = level,
            initiallyValidMoves = LevelSolver.initiallyValidMoves(level),
            solutionLength = solved?.order?.size ?: 0,
            solvable = solved != null && LevelSolver.verify(level, solved.order),
            effort = scanningEffort(level)
        )
    }

    /** Averaged over fixed-seed random clears, so the report is reproducible. */
    private fun scanningEffort(level: Level, samples: Int = 120): Double {
        val random = Random(seed = level.id.toLong() * 31 + 7)
        var total = 0.0
        repeat(samples) {
            var board = level.arrows
            var run = 0.0
            while (board.isNotEmpty()) {
                val free = board.filter { MoveValidator.canEscape(it, board) }
                if (free.isEmpty()) return Double.NaN
                run += board.size.toDouble() / free.size
                val taken = free[random.nextInt(free.size)]
                board = board.filterNot { it.id == taken.id }
            }
            total += run
        }
        return total / samples
    }

    @Test
    fun `the difficulty report is written and the curve has no cliffs`() {
        val rows = Levels.ALL.map(::analyse)

        val report = buildString {
            appendLine("# Arrow Escape — level difficulty report")
            appendLine()
            appendLine("Generated by `LevelDifficultyReportTest`. Development only — not shown in the app.")
            appendLine()
            appendLine("`effort` is the scanning work a clear takes: summed `remaining / free` over a")
            appendLine("full solve, averaged over 120 random clears. `step` is the jump from the")
            appendLine("previous level.")
            appendLine()
            appendLine("| Level | Board | Arrows | Initial moves | Solution length | Solvable | Effort | Step |")
            appendLine("|------:|:-----:|-------:|--------------:|----------------:|:--------:|-------:|-----:|")
            rows.forEachIndexed { index, row ->
                val step = if (index == 0) {
                    "—"
                } else {
                    val previous = rows[index - 1].effort
                    format("%+.0f%%", (row.effort / previous - 1.0) * 100)
                }
                appendLine(
                    "| ${row.level.id} " +
                        "| ${row.level.rows}×${row.level.columns} " +
                        "| ${row.level.arrows.size} " +
                        "| ${row.initiallyValidMoves} " +
                        "| ${row.solutionLength} " +
                        "| ${if (row.solvable) "yes" else "**NO**"} " +
                        "| ${format("%.1f", row.effort)} " +
                        "| $step |"
                )
            }
            appendLine()
            appendLine("Total arrows across the catalogue: ${rows.sumOf { it.level.arrows.size }}.")
        }

        val out = File("build/reports/levels/level-difficulty.md")
        out.parentFile?.mkdirs()
        out.writeText(report)
        println(report)

        // Every level solvable, and no step in the curve is a spike.
        rows.forEach { assertTrue("${it.level.name} is not solvable", it.solvable) }
        rows.zipWithNext { previous, current ->
            val growth = current.effort / previous.effort
            if (current.level.id in BREATHERS) {
                // The one planned dip in a world: a few percent easier than the level
                // before it, never a collapse. Every other step still climbs.
                assertTrue(
                    "${current.level.name} is a breather but not easier than ${previous.level.name} " +
                        "(${format("%.1f", current.effort)} vs ${format("%.1f", previous.effort)})",
                    growth < 1.0
                )
                assertTrue(
                    "${current.level.name} is more than a breather below ${previous.level.name} " +
                        "(${format("%.1f", previous.effort)} → ${format("%.1f", current.effort)})",
                    growth >= 0.90
                )
            } else {
                assertTrue(
                    "${current.level.name} is easier than ${previous.level.name} " +
                        "(${format("%.1f", current.effort)} vs ${format("%.1f", previous.effort)})",
                    growth >= 1.0
                )
            }
            // Level 2 is allowed a big relative jump: level 1 is deliberately tiny.
            val ceiling = if (current.level.id <= 2) 2.2 else 1.35
            assertTrue(
                "${current.level.name} is a difficulty spike after ${previous.level.name} " +
                    "(${format("%.1f", previous.effort)} → ${format("%.1f", current.effort)})",
                growth <= ceiling
            )
        }
    }

    private companion object {
        /**
         * The fifth level of each world is its breather: a little easier than the one
         * before, so the world's finale lands as a rise rather than another step of
         * the same ramp. Pinned here so a re-author cannot quietly lose the rhythm.
         */
        val BREATHERS = setOf(5, 11, 17, 23, 29)
    }

    private fun format(pattern: String, vararg args: Any) =
        String.format(Locale.ROOT, pattern, *args)
}
